### ISSUE TITLE
Create a status attribute for load or drosher.

### ISSUE THREAD

**Issue by HrushikC** [HrushikC/londree#8]
Create a Choice field attribute with the choices: "Full", "Vacant", "Ready" for one of the two models.

**Comment by rahulbhatt1899** [comment]
Hey, could you provide more information on this issue, I would like to contribute!

**Comment by HrushikC** [comment]
We'll update the readme soon so you get a better general idea of what this project is about, but for this issue, we basically want a new column in one of the models/tables of our SQLAlchemy Database

**Comment by rahulbhatt1899** [comment]
Something like this works?
`choice = db.Column(db.Integer, nullable=False)`
Assuming the choices would be stored as 0, 1, 2.
If not string works too.

**Comment by HrushikC** [comment]
Yes, this works. Later on, we would want to change the display on an html page based on which choice is selected so that we can show something like: 

Washer 1
Status: Full/Vacant/Ready

Basically, storing integers works, but we'd just have to map them to string values in routes.py. So I would go ahead with what you have, but just add a comment showing which integer maps to which option or something. Also add min=0 and max=2 as parameters because we only want 3 options for the attribute

**Comment by rahulbhatt1899** [comment]
Sure that works, could you assign this issue to me?
